### ISSUE TITLE
.doxityrc not found or unreadable

### ISSUE THREAD

**Issue by elmutt** [DigixGlobal/doxity#10]
When running "doxity develop" it gives the error ".doxityrc not found or unreadable" even when the file does exist with the provided example content

**Comment by vitiko** [comment]
i think you need to remove comments from example content of  .doxityrc file https://github.com/DigixGlobal/doxity#doxityrc

**Comment by yudilevi** [comment]
Also, there's a missing comma right after the `interaction` block.

**Comment by hitchcott** [comment]
The file should be generated properly now with `doxity init`
