### ISSUE TITLE
Solidity >0.4.18

### ISSUE THREAD

**Issue by decanus** [DigixGlobal/doxity#22]
Can we get the solidity version updated, so that support for interface contracts is enabled.

**Comment by roynalnaruto** [comment]
Hi @decanus I have updated this in the `doxity-latest` branch.

You can use `@digix/doxity-solc: 0.6.0` as a dependency in your project. It will support truffle projects, as well as the `0.4.24` version of solc

Please have a look at how we have used doxity in [our repository](https://github.com/DigixGlobal/dao-contracts)

Also have a look at [my comment](https://github.com/DigixGlobal/doxity/issues/25#issuecomment-417222129) for step by step setup.
