### ISSUE TITLE
solc - command not found.

### ISSUE THREAD

**Issue by andylockran** [DigixGlobal/doxity#4]
➜  openprep git:(master) ✗ ./node_modules/.bin/doxity build
solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
/bin/sh: solc: command not found

```sudo npm -g install solc``` - ends up with a `solcjs` binary, not `solc`.

How do I get the solc binary?

**Comment by hitchcott** [comment]
Hi There,

Yeah, doxity requires native `solc` as `solc-js` doesn't support the natspec flags yet.

Installation instructions are over at: http://solidity.readthedocs.io/en/develop/installing-solidity.html under 'binary packages'
