### ISSUE TITLE
Doxity init creates scripts folder but nothing else

### ISSUE THREAD

**Issue by elmutt** [DigixGlobal/doxity#9]
Running "doxity init" creates an empty scripts folder and nothing else.

**Comment by hitchcott** [comment]
Hi There,

Thanks for the report. What's your OS and doxity version?

Cheers,

**Comment by elmutt** [comment]
Hi Chris,

OSX El Capitan.  Doxity v0.3.2

Thanks,

Sean

**Comment by cag** [comment]
I got this error as well. This is the response in the console.

```
$ doxity init
.doxityrc not found or unreadable
Getting "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/37f63a26c2664c31f4463a49af939ddb6e2181e7.tar.gz...
(node:7760) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Invalid URI "%22https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/37f63a26c2664c31f4463a49af939ddb6e2181e7.tar.gz"
(node:7760) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is a workaround:

```bash
doxity init --source https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/37f63a26c2664c31f4463a49af939ddb6e2181e7.tar.gz
```

**Comment by hitchcott** [comment]
Thanks for the and finding a workaround @cag.

I'm putting doxity on a temporary hold for the moment, as it depends on the native compiler, which doesn't work with truffle imports. I will address this issue once that upgrade is completed.

**Comment by yudilevi** [comment]
Is the project still on hold?

**Comment by tymat** [comment]
What version of solidity are you using?  @yudilevi

**Comment by yudilevi** [comment]
Latest, 0.4.11

**Comment by tymat** [comment]
Do you have doxity 0.5.0?  

Also what is in your .doxityrc file?

**Comment by yudilevi** [comment]
I just installed doxity, latest version (globally).
I didn't use any .doxityrc file - which as I understand uses the defaults.
I also tried using the file but doxity can't find it - I assume because I'm on a windows machine and process.env.PWD is undefined.
I tried to define PWD manually but still no go.

**Comment by tymat** [comment]
What version of nodejs do you have on your machine?

**Comment by yudilevi** [comment]
node v7.9.0.

And correction about .doxityrc - after setting up process.env.PWD, `doxity init` seems to find the file, but still stuck in `Getting https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/9445d59056058159ce25d7cd1643039523718553.tar.gz...`

**Comment by tymat** [comment]
```
{
  "target": "scripts/doxity",
  "src": "contracts/*",
  "dir": "pages/docs",
  "source": "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz",
  "out": "docs"
}
```

You can try the following .doxityrc

**Comment by yudilevi** [comment]
Same result - scripts folder is created, stuck at `Getting https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/9445d59056058159ce25d7cd1643039523718553.tar.gz...`

**Comment by yudilevi** [comment]
One possible explanation would be that this -
`.pipe(targz().createWriteStream(tmpTarget))`

Doesn't actually create the entire directory tree, but only creates a single directory and then fails but haven't debugged it yet.

**Comment by hitchcott** [comment]
Doxity is not on hold and should be working with truffle projects. This will be added as a low-priority TODO for now as unfortunately we're not using windows. Do feel free to submit PRs if you'd like to add windows support more quickly.
